# Generated by Django 4.1.7 on 2023-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
