# Generated by Django 4.1.7 on 2023-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_shippingaddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
