# Generated by Django 4.1.7 on 2023-03-20 09:56

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=1500),
        ),
    ]
